version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:       
      - "8080:8080"     
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
    command: sh -c "yarn dev"