version: "3.9"
services:
  web:
    build: .
    ports: 
      - "8080:8080"
      - "8081:8081"
      - "35729:35729" 
    volumes:
      - ./:/usr/src/app
    environment:
      - CONTENFUL_SPACE=${CONTENFUL_SPACE}
      - CONTENFUL_ENVIRONMENT=${CONTENFUL_ENVIRONMENT}
      - CONTENFUL_ACCESS_TOKEN=${CONTENFUL_ACCESS_TOKEN}
      - BLOG_URL=${BLOG_URL}